### ISSUE TITLE
Github desktop commit 失败

### ISSUE THREAD

**Issue by CooperChen453** [swsoyee/rPackageTutorial#1]
本人使用windows操作系统，在按照教程进行学习的过程中，使用github desktop进行代码远程的提交，结果出现如下乱码提示，查询了一些网上可能类似的错误，但是目前没有找到解决方案。感觉和R环境关系不大？可能是github desktop在windows下的问题？麻烦看一下~谢谢！（以下是github desktop显示错误的界面）
<img width="723" alt="error in github desktop" src="https://user-images.githubusercontent.com/46716251/115526120-49c5ff80-a2c2-11eb-9dc7-72ea8fd921a9.png">

**Comment by swsoyee** [comment]
我曾经用过 Windows，用 GitHub Desktop 是没问题的。
我猜测是不是在 Windows 下安装过 Linux 引起的问题？

https://docs.microsoft.com/zh-cn/windows/wsl/

**Comment by CooperChen453** [comment]
> 我曾经用过 Windows，用 GitHub Desktop 是没问题的。
> 我猜测是不是在 Windows 下安装过 Linux 引起的问题？
> 
> https://docs.microsoft.com/zh-cn/windows/wsl/

之前有安装过Linux，但是之后都删除了。我再看看，谢谢~
